apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: vprofile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofile
        image:  padhudockerpractice/vprofile:latest
        ports:
        - containerPort: 8080



          #sevices


apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: vprofile
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080          
